name: fluid_ui_design_example
description: A framework for building Fluid Resopnsive UIs in Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.2.1
  flutter_svg: ^2.0.6
  google_fonts: ^4.0.5
  fluid_ui_design: 
    path: ../

flutter:
  uses-material-design: true
  assets: 
    - assets/logo/