name: fluid_ui_design
description: A framework for building Fluid Responsive UIs in Flutter.
homepage: https://github.com/DutchCodingCompany/fluid_ui_design

version: 0.0.1-beta.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  parameterized_test: ^1.0.0
  

flutter:
  uses-material-design: true
  